import type { Metadata } from "next";
import { inter } from "@/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Atus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
