import type { Metadata } from "next";
import { inter } from "@/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Atus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en" className='hidden'>
      <head>
        <link rel="preload" href="/atus_light.svg" as="image"/>
        <link rel="preload" href="/atus_dark.svg" as="image"/>
      </head>
      <body className={inter.className}>{children}</body>
      </html>
  );
}
